<?php $this->loadConfigValues(); ?>

<form action="<?php echo _url('extension', 'configure', 'e', urlencode($this->getName())); ?>" method="post">
	<input type="hidden" name="_csrf" value="<?php echo FreshRSS_Auth::csrfToken(); ?>" />
	<div class="form-group">

		<label class="group-name" for="yt_height"><?php echo _t('ext.yt_videos.height'); ?></label>
		<div class="group-controls">
			<input type="number" id="yt_height" name="yt_height" value="<?php echo $this->getHeight(); ?>" min="50" data-leave-validation="1">
		</div>

		<label class="group-name" for="yt_width"><?php echo _t('ext.yt_videos.width'); ?></label>
		<div class="group-controls">
			<input type="number" id="yt_width" name="yt_width" value="<?php echo $this->getWidth(); ?>" min="100" data-leave-validation="1">
		</div>
		
		<label class="group-name" for="yt_content_none"><?php echo _t('ext.yt_videos.content.title'); ?></label>
		<div class="group-controls">
			<label for="yt_content_none">
				<input type="radio" id="yt_content_none" name="yt_content_choice" value="none" <?= $this->getContentHandling() === 'none' ? 'checked' : '' ?>>
				<?php echo _t('ext.yt_videos.content.none'); ?>
			</label>
			<label for="yt_content_append">
				<input type="radio" id="yt_content_append" name="yt_content_choice" value="append" <?= $this->getContentHandling() === 'append' ? 'checked' : '' ?>>
				<?php echo _t('ext.yt_videos.content.append'); ?>
			</label>
			<label for="yt_content_format">
				<input type="radio" id="yt_content_format" name="yt_content_choice" value="format" <?= $this->getContentHandling() === 'format' ? 'checked' : '' ?>>
				<?php echo _t('ext.yt_videos.content.format'); ?>
			</label>
		</div>

		<label class="group-name" for="yt_nocookie"><?php echo _t('ext.yt_videos.use_nocookie'); ?></label>
		<div class="group-controls">
			<input type="checkbox" id="yt_nocookie" name="yt_nocookie" value="1" <?php if ($this->getUseNoCookie()) { echo 'checked'; }; ?>>
		</div>
	</div>

	<div class="form-group form-actions">
		<div class="group-controls">
			<button type="submit" class="btn btn-important"><?php echo _t('gen.action.submit'); ?></button>
			<button type="reset" class="btn"><?php echo _t('gen.action.cancel'); ?></button>
		</div>
	</div>
</form>

<p>
	<?php echo _t('ext.yt_videos.updates'); ?>
	<a href="https://github.com/kevinpapst/freshrss-youtube" target="_blank">GitHub</a>.
</p>
